CREATE DATABASE AVANTHI;
USE AVANTHI;
CREATE TABLE EMPDATA(
EMPID INT, EMPNAME Varchar(20), EMPDEPT VARCHAR(20), EMPPHNO INT, EMPSALARY INT);
INSERT INTO EMPDATA VALUES
(401, "PREESHA", "ECE", 758924, 36000),
(301, "AAROHI", "MECH", 75554, 32000),
(501, "AKSHARA", "CSE", 751694, 34000),
(505, "RUHI", "CSE", 521975, 39000),
(304, "NAIRA","MECH", 581455, 4000);
SELECT *FROM EMPDATA;
SELECT DISTINCT EMPDEPT, EMPID FROM EMPDATA;
SELECT COUNT(DISTINCT EMPDEPT) FROM EMPDATA;
SELECT *FROM EMPDATA
WHERE  EMPNAME= "PREESHA";
SELECT *FROM EMPDATA
WHERE EMPID=304;
SELECT *FROM EMPDATA 
WHERE EMPID>400;
SELECT *FROM EMPDATA
ORDER BY EMPID;
SELECT *FROM EMPDATA
ORDER BY EMPDEPT ASC;
SELECT *FROM EMPDATA
ORDER BY EMPID ASC, EMPSALARY DESC;
SELECT *FROM EMPDATA
WHERE EMPNAME="PREESHA" AND EMPDEPT LIKE "E%";
SELECT *FROM EMPDATA
WHERE EMPID= 301 AND  EMPNAME="AAROHI" AND EMPDEPT="MECH";
SELECT *FROM EMPDATA
WHERE EMPNAME= "AAROHI" AND EMPDEPT="MECH" OR EMPID= 401;
SELECT *FROM EMPDATA
WHERE EMPID=401 OR EMPNAME="AKSHARA";
SELECT *FROM EMPDATA
WHERE EMPID=505 AND EMPPHNO=521975 OR EMPNAME LIKE "R%";
SELECT *FROM EMPDATA
WHERE  NOT EMPID = 401;

